# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSgucardanapolis():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_sgucardanapolis(self):
    # Test name: sgucard_anapolis
    # Step # | name | target | value
    # 1 | open | /cmagnet/Login.do | 
    self.driver.get("https://sgucard.unimedanapolis.com.br/cmagnet/Login.do")
    # 2 | setWindowSize | 1058x804 | 
    self.driver.set_window_size(1058, 804)
    # 3 | type | id=login | 70205235107
    self.driver.find_element(By.ID, "login").send_keys("70205235107")
    # 4 | type | id=passwordTemp | Baet@270424
    self.driver.find_element(By.ID, "passwordTemp").send_keys("Baet@270424")
    # 5 | click | id=login | 
    self.driver.find_element(By.ID, "login").click()
    # 6 | click | id=passwordTemp | 
    self.driver.find_element(By.ID, "passwordTemp").click()
    # 7 | click | id=Button_DoLogin | 
    self.driver.find_element(By.ID, "Button_DoLogin").click()
    # 8 | click | css=#centro_61 img | 
    self.driver.find_element(By.CSS_SELECTOR, "#centro_61 img").click()
    # 9 | click | id=mainMenuItem2 | 
    self.driver.find_element(By.ID, "mainMenuItem2").click()
    # 10 | click | css=.MagnetoBigRoundedButtonLeft | 
    self.vars["window_handles"] = self.driver.window_handles
    # 11 | storeWindowHandle | root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MagnetoBigRoundedButtonLeft").click()
    # 12 | selectWindow | handle=${win8001} | 
    self.vars["win8001"] = self.wait_for_window(2000)
    # 13 | close |  | 
    self.vars["root"] = self.driver.current_window_handle
    # 14 | selectWindow | handle=${root} | 
    self.driver.switch_to.window(self.vars["win8001"])
    # 15 | click | css=#centro_21 .MagnetoSubMenuTittle | 
    self.driver.close()
    # 16 | click | xpath=//tr[2]/td[2]/a | 
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, "#centro_21 .MagnetoSubMenuTittle").click()
    self.driver.find_element(By.XPATH, "//tr[2]/td[2]/a").click()
  
