# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFiltroguia():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_filtroguia(self):
    # Test name: filtro guia
    # Step # | name | target | value
    # 1 | click | name=s_nr_guia | 
    self.driver.find_element(By.NAME, "s_nr_guia").click()
    # 2 | type | name=s_nr_guia | 15703510
    self.driver.find_element(By.NAME, "s_nr_guia").send_keys("numero_guia")
    # 3 | click | name=Button_FIltro | 
    self.driver.find_element(By.NAME, "Button_FIltro").click()
    # 4 | click | xpath=//tr[@id='trRow_2']/td[2] | 
    self.driver.find_element(By.XPATH, "//tr[@id=\'trRow_2\']/td[2]").click()
    # 5 | click | xpath=//tr[@id='trRow_2']/td[3]/a | 
    self.driver.find_element(By.XPATH, "//tr[@id=\'trRow_2\']/td[3]/a").click()
  
