# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTesteexec():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_testeexec(self):
    # Test name: teste exec
    # Step # | name | target | value   

    # 1 | click | id=mainMenuItem2 | 
    self.driver.find_element(By.ID, "mainMenuItem2").click()
    # 2 | waitForElementVisible | xpath=//input[@name='s_nr_guia'] | 1000
    WebDriverWait(self.driver, 1000).until(expected_conditions.visibility_of_element_located((By.XPATH, "//input[@name=\'s_nr_guia\']")))
    # 3 | click | xpath=//input[@name='s_nr_guia'] | 
    self.driver.find_element(By.XPATH, "//input[@name=\'s_nr_guia\']").clear()
    self.driver.find_element(By.XPATH, "//input[@name=\'s_nr_guia\']").click()
    # 4 | type | xpath=//input[@name='s_nr_guia'] | 15838772
    self.driver.find_element(By.XPATH, "//input[@name=\'s_nr_guia\']").send_keys(agendamento.guia)
    # 5 | click | name=Button_FIltro | 
    self.driver.find_element(By.NAME, "Button_FIltro").click()
    # 6 | click | linkText=15768675 | 
    self.driver.find_element(By.LINK_TEXT, agendamento.guia).click()
    # 7 | click | id=DM_TP_ATEND_SADT | 
    self.driver.find_element(By.ID, "DM_TP_ATEND_SADT").click()
    # 8 | select | id=DM_TP_ATEND_SADT | label=03 - Outras Terapias
    dropdown = self.driver.find_element(By.ID, "DM_TP_ATEND_SADT")
    dropdown.find_element(By.XPATH, "//option[. = '03 - Outras Terapias']").click()
    # 9 | click | id=DM_REGIME_ATEND | 
    self.driver.find_element(By.ID, "DM_REGIME_ATEND").click()
    # 10 | select | id=DM_REGIME_ATEND | label=01 - Ambulatorial
    dropdown = self.driver.find_element(By.ID, "DM_REGIME_ATEND")
    dropdown.find_element(By.XPATH, "//option[. = '01 - Ambulatorial']").click()
    # 11 | click | id=dt_serie_1 | 
    self.driver.find_element(By.ID, "dt_serie_1").click()
    # 12 | type | id=dt_serie_1 | 27/02/2026 15:00
    self.driver.find_element(By.ID, "dt_serie_1").send_keys(agendamento.data_hora)
    # 13 | click | id=Button_Gravar | 
    self.vars["window_handles"] = self.driver.window_handles
    # 14 | storeWindowHandle | root | 
    self.driver.find_element(By.ID, "Button_Gravar").click()
    # 15 | selectWindow | handle=${win7440} | 
    self.vars["win7440"] = self.wait_for_window(2000)
    # 16 | close |  | 
    self.vars["root"] = self.driver.current_window_handle
    # 17 | selectWindow | handle=${root} | 
    self.driver.switch_to.window(self.vars["win7440"])
    # 18 | click | css=.grid-menu:nth-child(1) img | 
    self.driver.close()
    # 19 | click | css=.MagnetoRoundedButtonLink:nth-child(1) .MagnetoBigRoundedButtonRight | 
    self.driver.switch_to.window(self.vars["root"])
    # 20 | click | css=#link_busca_prest > img | 
    self.driver.find_element(By.CSS_SELECTOR, ".grid-menu:nth-child(1) img").click()
    # 21 | selectWindow | handle=${win2183} | 
    self.driver.find_element(By.CSS_SELECTOR, ".MagnetoRoundedButtonLink:nth-child(1) .MagnetoBigRoundedButtonRight").click()
    # 22 | click | name=s_nm_prestador | 
    self.vars["window_handles"] = self.driver.window_handles
    # 23 | type | name=s_nm_prestador | werla
    self.driver.find_element(By.CSS_SELECTOR, "#link_busca_prest > img").click()
    # 24 | click | name=s_tp_conselho | 
    self.vars["win2183"] = self.wait_for_window(2000)
    # 25 | select | name=s_tp_conselho | label=CREFONO - Conselho Regional de Fonoaudiologia
    self.driver.switch_to.window(self.vars["win2183"])
    # 26 | click | id=s_tp_busca_Options | 
    self.driver.find_element(By.NAME, "s_nm_prestador").click()
    # 27 | select | id=s_tp_busca_Options | label=Prestador Externo
    self.driver.find_element(By.NAME, "s_nm_prestador").send_keys(agendamento.prestador)
    # 28 | click | name=Button_DoSearch | 
    self.driver.find_element(By.NAME, "s_tp_conselho").click()
    # 29 | click | xpath=//div[@id='conteudo-submenu']/table/tbody/tr[3]/td[2]/a | 
    dropdown = self.driver.find_element(By.NAME, "s_tp_conselho")
    dropdown.find_element(By.XPATH, "//option[. = 'CREFONO - Conselho Regional de Fonoaudiologia']").click()
    # 30 | close |  | 
    self.driver.find_element(By.ID, "s_tp_busca_Options").click()
    # 31 | selectWindow | handle=${root} | 
    dropdown = self.driver.find_element(By.ID, "s_tp_busca_Options")
    dropdown.find_element(By.XPATH, "//option[. = 'Prestador Externo']").click()
    # 32 | click | name=Button_Insert | 
    self.driver.find_element(By.NAME, "Button_DoSearch").click()
    # 33 | click | id=DM_GRAU_PARTIC_1 | 
    self.driver.find_element(By.XPATH, "//div[@id=\'conteudo-submenu\']/table/tbody/tr[3]/td[2]/a").click()
    # 34 | select | id=DM_GRAU_PARTIC_1 | label=12 - Clínico
    self.driver.close()
    # 35 | click | id=NR_SEQ_ITEM_1 | 
    self.driver.switch_to.window(self.vars["root"])
    # 36 | select | id=NR_SEQ_ITEM_1 | label=2250005170 - TERAPIA ABA - TERAPIA OCUPACIO
    self.driver.find_element(By.NAME, "Button_Insert").click()
    # 37 | click | id=Button_Submit | 
    self.driver.find_element(By.ID, "DM_GRAU_PARTIC_1").click()
    # 38 | click | css=.MagnetoRoundedButtonLink:nth-child(2) .MagnetoBigRoundedButtonRight | 
    dropdown = self.driver.find_element(By.ID, "DM_GRAU_PARTIC_1")
    dropdown.find_element(By.XPATH, "//option[. = '12 - Clínico']").click()
    # 39 | mouseOver | id=Button_Parcial | 
    self.driver.find_element(By.ID, "NR_SEQ_ITEM_1").click()
    dropdown = self.driver.find_element(By.ID, "NR_SEQ_ITEM_1")
    dropdown.find_element(By.XPATH, "//option[. = '2250005170 - TERAPIA ABA - TERAPIA OCUPACIO']").click()
    self.driver.find_element(By.ID, "Button_Submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".MagnetoRoundedButtonLink:nth-child(2) .MagnetoBigRoundedButtonRight").click()
    element = self.driver.find_element(By.ID, "Button_Parcial")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
