# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestExcluir():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_excluir(self):
    # Test name: excluir
    # Step # | name | target | value | comment
    self.driver.find_element(By.XPATH, "//*[@id="trRow_2"]/td[1]/input[1]").click()
    # 1 | click | id=Btn_Excluir |  | 
    self.driver.find_element(By.ID, "Btn_Excluir").click()
    # 2 | assertConfirmation | Confirmar exclusão dos registros selecionados? |  | 
    assert self.driver.switch_to.alert.text == "Confirmar exclusão dos registros selecionados?"
    # 3 | webdriverChooseOkOnVisibleConfirmation |  |  | 
    self.driver.switch_to.alert.accept()
  
